
[colors.bright]
black = "#505050"
blue = "#729FCF"
cyan = "#34E2E2"
green = "#8AE234"
magenta = "#AD7FA8"
red = "#EF2929"
white = "#ffffff"
yellow = "#FCE94F"

[colors.normal]
black = "#555753"
blue = "#3465A4"
cyan = "#06989A"
green = "#4E9A06"
magenta = "#75507B"
red = "#CC0000"
white = "#b0b0b0"
yellow = "#C4A000"

[colors.primary]
foreground = "#BABDB6"
background = "#020202"

[font]
#builtin_box_drawing = true
#size = 9
#offset = { y = -1 }
#glyph_offset = { y = -1 }

[font.normal]
#family = "RobotoMono"
family = "Monaco for Powerline"
#family = "Iosevka"
#family = "UbuntuSansM Nerd Font"
#family = "NotoSansM Nerd Font"
#family = "Cousine Nerd Font"
#style = "Condensed"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0002%"
key = "e"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002\""
key = "o"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002c"
key = "n"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002z"
key = "x"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002c"
key = "t"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002p"
key = "Left"
mods = "Super"

[[keyboard.bindings]]
chars = "\u0002p"
key = "h"
mods = "Super"

[[keyboard.bindings]]
chars = "\u0002n"
key = "Right"
mods = "Super"

[[keyboard.bindings]]
chars = "\u0002n"
key = "l"
mods = "Super"

[[keyboard.bindings]]
chars = "\u0002\u0010"
key = "Left"
mods = "Super|Shift"

[[keyboard.bindings]]
chars = "\u0002\u0010"
key = "h"
mods = "Super|Shift"

[[keyboard.bindings]]
chars = "\u0002\u000e"
key = "Right"
mods = "Super|Shift"

[[keyboard.bindings]]
chars = "\u0002\u000e"
key = "l"
mods = "Super|Shift"

[[keyboard.bindings]]
action = "None"
key = "b"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002p"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002n"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "Equals"
mods = "Control"

## Deactivate Ctrl+Shift space as I don't need alacritty to scroll
## or have there own substitute to copy mode from tmux

[[keyboard.bindings]]
action = "None"
key = "Space"
mods = "Control|Shift"

## Same, I don't need to search forward or backwards in the scroll history
## of alacritty

[[keyboard.bindings]]         # disable Ctrl-Shift-F (SearchForward)
key    = "F"
mods   = "Control|Shift"
action = "None"

[[keyboard.bindings]]         # disable Ctrl-Shift-B (SearchBackward)
key    = "B"
mods   = "Control|Shift"
action = "None"


[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"


[scrolling]
history = 0


[terminal.shell]
args = ["new-session", "-A", "-s", "main"]
program = "tmux"

[window]
decorations = "None"
startup_mode = "Maximized"

padding = { x = 1, y = 2 }

[general]
import = [
  "~/.config/alacritty/local.toml",
]


[terminal]

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
regex = "(audioplay://|ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
binding = { key = "L", mods = "Control|Shift" }
